### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by catalinaadam** [percona/pmm-doc#888]
You can fix typos, spelling mistakes, or grammatical errors in the documentation.
If you want to make a bigger change, create a new issue instead and assign someone from the documentation team to review the changes: @catalinaadam  or @rasika-chivate.

Percona follows the principle of simple documentation. For information on this, check out the [Percona Documentation Style Guide](https://percona-style-guide.onrender.com/overview.html)

**Comment by arjun434** [comment]
Hey please assign this task to me.

**Comment by akhil9281** [comment]
I would like to work on this.

**Comment by catalinaadam** [comment]
Hi there. Thank you for your interest in working on this issue. 
This is a general issue, so it's always open. You can just provide you PRs and we'll  review and accept them as soon as possible.
Thank you!
@arjun434 @akhil9281

**Comment by catalinaadam** [comment]
Hi there. Thank you for your interest in working on this issue. 
This is a general issue, so it's always open. You can just provide you PRs and we'll  review and accept them as soon as possible.
Thank you!
@arjun434 @akhil9281

**Comment by GloriaOkeke** [comment]
Can I also work on this please? @catalinaadam

**Comment by catalinaadam** [comment]
> Can I also work on this please? @catalinaadam

Sure, @GloriaOkeke. Please create a PR similar to [@natastro's PR](https://github.com/percona/pmm-doc/pull/891).

**Comment by Ski1ledHawkeye** [comment]
Hey, can you assign this issue to me. It will be my first one. Please....

**Comment by Leigh-Ola** [comment]
@catalinaadam  Please check out my pull request at #899
