### ISSUE TITLE
pmmserver升级container中postgresql迁移报错

### ISSUE THREAD

**Issue by dbcmp** [percona/pmm-doc#892]
INFO[2022-10-19T06:31:13.718+00:00] Migrating database...                         component=migration
WARN[2022-10-19T06:31:13.718+00:00] Failed to migrate database: dial tcp 127.0.0.1:5432: connect: connection refused.  component=migration
INFO[2022-10-19T06:31:14.718+00:00] Migrating database...                         component=migration
WARN[2022-10-19T06:31:14.718+00:00] Failed to migrate database: dial tcp 127.0.0.1:5432: connect: connection refused.  component=migration
INFO[2022-10-19T06:31:15.719+00:00] Migrating database...                         component=migration
WARN[2022-10-19T06:31:15.720+00:00] Failed to migrate database: dial tcp 127.0.0.1:5432: connect: connection refused.  component=migration
INFO[2022-10-19T06:31:16.720+00:00] Migrating database...

**Comment by dba-ws** [comment]
TASK [Upgrade grafana database (Get the latest schema)] ************************
changed: [localhost]

TASK [Install postgres] ********************************************************

TASK [postgres : Add PostgreSQL 14 YUM repository] *****************************
changed: [localhost]

TASK [postgres : Add PostgreSQL 11 YUM repository] *****************************
ok: [localhost]

TASK [postgres : Install Postgres] *********************************************
changed: [localhost]

TASK [postgres : Create Postgres log file] *************************************
changed: [localhost]

TASK [Add the user 'postgres' to group 'pmm'] **********************************
ok: [localhost]

TASK [postgres : Check if Postgres 14 directory exists] ************************
ok: [localhost]

TASK [postgres : Create Postgres data dir] *************************************
changed: [localhost]

TASK [postgres : Initialize Postgres database] *********************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "su: cannot open session: Permission denied\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
localhost                  : ok=20   changed=12   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

**Comment by igroene** [comment]
This is the documentation page. Please open a bug at https://jira.percona.com/jira/software/c/projects/PMM
