### ISSUE TITLE
Fix Headline Hierarchy for Subsections of Slow query log

### ISSUE THREAD

**Issue by Johnson145** [percona/pmm-doc#979]
The sections [Applicable versions](https://docs.percona.com/percona-monitoring-and-management/setting-up/client/mysql.html#applicable-versions) etc. following the [Slow query log](https://docs.percona.com/percona-monitoring-and-management/setting-up/client/mysql.html#slow-query-log) paragraph refer to the latter only. Thus, they should be nested below it, but are shown on the same level right now.

PS: I hope it's okay that I'm creating an issue for this detail. If I got time, I may provide a PR later on. Just didn't want to forget sharing this information.

**Comment by igroene** [comment]
addressed by https://github.com/percona/pmm-doc/pull/1294/
